title: Adriano Amalfi - Personal Site
baseurl: /
permalink: '/:title/'
layout_style: overflow
palette: blue
header:
  title: Adriano Amalfi
  tagline: Personal Site
  profile_img: /images/adriano.jpg
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; Adriano Amalfi All rights reserved.'
  links:
    - text: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
    - new_window: true
      text: 'Github Hosting '
      url: 'https://github.com'
    - new_window: true
      text: Netlify Devops
      url: '#'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: '/posts/:title/'
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
